[project]
name = "dexpter"
version = "0.1.0"
description = "Lightweight, flexible JSON-backed data science experiment tracker"
requires-python = ">=3.9"

[project.scripts]
dexpter = "dexpter.cli:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
